# Generated by Django 6.0.3 on 2026-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="sentiment_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
